//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company()
        {
            this.shareholders = new HashSet<shareholder>();
        }
    
        public decimal comp_id { get; set; }
        public string company_name { get; set; }
        public string reg_no { get; set; }
        public string national_code { get; set; }
        public string address { get; set; }
        public string postal_code { get; set; }
        public string tel { get; set; }
        public string bank_acc_desc { get; set; }
        public string end_date_s { get; set; }
        public string end_date_e { get; set; }
        public Nullable<decimal> share_amnt { get; set; }
        public string cap_percent { get; set; }
        public Nullable<decimal> pre_cap_amnt { get; set; }
        public Nullable<decimal> cap_amnt { get; set; }
        public string share_type { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string form_type { get; set; }
        public string form_path { get; set; }
        public string login_message { get; set; }
        public string link_add_1 { get; set; }
        public string link_add_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shareholder> shareholders { get; set; }
    }
}
