//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class shareholder
    {
        public string shrh_code { get; set; }
        public decimal comp_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string father { get; set; }
        public string cert_no { get; set; }
        public string nat_code { get; set; }
        public string bbs_code { get; set; }
        public string mobile { get; set; }
        public string s_address { get; set; }
        public string s_postal_code { get; set; }
        public Nullable<long> share { get; set; }
        public Nullable<long> spri_qunt { get; set; }
        public Nullable<decimal> spri_amnt { get; set; }
        public Nullable<decimal> credit_amnt { get; set; }
        public Nullable<decimal> pay_amnt { get; set; }
        public string password { get; set; }
        public string print_flag { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string pay_id { get; set; }
        public string kind { get; set; }
    
        public virtual company company { get; set; }
    }
}
